name: multiple_result
description: Multiple results for dart. Inspired by dartz's Either and Kotlin's sealed classes
version: 5.1.0
repository: https://github.com/higorlapa/result

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: 1.24.4
  lints: 2.1.1
